import { createRecipe, recipeCount } from "./db.js";

const seedRecipes = [
  {
    name: "Sheet-Pan Lemon Herb Chicken Thighs",
    cuisine: "American",
    tags: ["High-protein", "Comfort", "Budget"],
    servings: 4,
    caloriesPerServing: 520,
    proteinPerServing: 42,
    estimatedCost: 11.5,
    cookTimeMin: 45,
    appliance: "Oven",
    method: "Roast seasoned chicken thighs and potatoes on one sheet pan until crisp and cooked through.",
    ingredients: [
      { name: "chicken thighs", quantity: "2 lb", category: "Meat & Seafood", estCost: 5.5 },
      { name: "baby potatoes", quantity: "1.5 lb", category: "Produce", estCost: 2.5 },
      { name: "lemon", quantity: "1", category: "Produce", estCost: 0.6 },
      { name: "garlic", quantity: "4 cloves", category: "Produce", estCost: 0.4 },
      { name: "olive oil", quantity: "3 tbsp", category: "Pantry", estCost: 0.5 },
      { name: "dried oregano", quantity: "1 tbsp", category: "Spices", estCost: 0.3 },
      { name: "fresh rosemary", quantity: "2 sprigs", category: "Produce", estCost: 1.7 },
    ],
    sides: [
      {
        name: "Garlic Green Beans",
        note: "Sauté green beans with garlic while the chicken rests.",
        estCost: 2.8,
        caloriesPerServing: 70,
        ingredients: [
          { name: "green beans", quantity: "1 lb", category: "Produce", estCost: 2.2 },
          { name: "garlic", quantity: "2 cloves", category: "Produce", estCost: 0.2 },
          { name: "olive oil", quantity: "1 tbsp", category: "Pantry", estCost: 0.2 },
          { name: "butter", quantity: "1 tbsp", category: "Dairy & Eggs", estCost: 0.2 },
        ],
      },
      {
        name: "Simple Side Salad",
        note: "Romaine, cucumber, and a quick lemon vinaigrette — bright against the roast.",
        estCost: 3.1,
        caloriesPerServing: 90,
        ingredients: [
          { name: "romaine lettuce", quantity: "1 head", category: "Produce", estCost: 1.8 },
          { name: "cucumber", quantity: "1", category: "Produce", estCost: 0.7 },
          { name: "lemon", quantity: "1/2", category: "Produce", estCost: 0.3 },
          { name: "olive oil", quantity: "2 tbsp", category: "Pantry", estCost: 0.3 },
        ],
      },
    ],
  },
  {
    name: "Weeknight Beef & Broccoli Stir-Fry",
    cuisine: "Asian",
    tags: ["Asian", "Quick", "High-protein"],
    servings: 4,
    caloriesPerServing: 480,
    proteinPerServing: 34,
    estimatedCost: 13.2,
    cookTimeMin: 25,
    appliance: "Stove",
    method: "Sear thin-sliced flank steak, toss with steamed broccoli in a soy-garlic-ginger sauce.",
    ingredients: [
      { name: "flank steak", quantity: "1.25 lb", category: "Meat & Seafood", estCost: 8.0 },
      { name: "broccoli", quantity: "1.5 lb", category: "Produce", estCost: 2.2 },
      { name: "soy sauce", quantity: "1/3 cup", category: "Pantry", estCost: 0.5 },
      { name: "garlic", quantity: "3 cloves", category: "Produce", estCost: 0.3 },
      { name: "fresh ginger", quantity: "1 tbsp", category: "Produce", estCost: 0.5 },
      { name: "cornstarch", quantity: "2 tbsp", category: "Pantry", estCost: 0.2 },
      { name: "brown sugar", quantity: "2 tbsp", category: "Pantry", estCost: 0.2 },
    ],
    sides: [
      {
        name: "Steamed Jasmine Rice",
        note: "The classic base — soaks up the extra sauce.",
        estCost: 1.0,
        caloriesPerServing: 200,
        ingredients: [
          { name: "jasmine rice", quantity: "2 cups dry", category: "Pantry", estCost: 1.0 },
        ],
      },
      {
        name: "Cucumber Sesame Salad",
        note: "Cool, crunchy contrast — toss cucumbers with rice vinegar and sesame.",
        estCost: 1.6,
        caloriesPerServing: 45,
        ingredients: [
          { name: "cucumber", quantity: "2", category: "Produce", estCost: 1.2 },
          { name: "rice vinegar", quantity: "2 tbsp", category: "Pantry", estCost: 0.2 },
          { name: "sesame seeds", quantity: "1 tsp", category: "Spices", estCost: 0.2 },
        ],
      },
    ],
  },
  {
    name: "Slow Cooker Chicken Tinga Tacos",
    cuisine: "Mexican",
    tags: ["Mexican", "Meal-prep", "Budget", "Kid-friendly"],
    servings: 6,
    caloriesPerServing: 430,
    proteinPerServing: 32,
    estimatedCost: 12.4,
    cookTimeMin: 240,
    appliance: "Crock pot",
    method: "Slow-cook chicken breasts in chipotle-tomato sauce, shred, and serve in warm tortillas.",
    ingredients: [
      { name: "chicken breasts", quantity: "2 lb", category: "Meat & Seafood", estCost: 6.0 },
      { name: "chipotle peppers in adobo", quantity: "1 small can", category: "Pantry", estCost: 1.5 },
      { name: "crushed tomatoes", quantity: "1 can (14 oz)", category: "Pantry", estCost: 1.1 },
      { name: "yellow onion", quantity: "1", category: "Produce", estCost: 0.7 },
      { name: "corn tortillas", quantity: "18", category: "Bakery", estCost: 2.5 },
      { name: "queso fresco", quantity: "4 oz", category: "Dairy & Eggs", estCost: 2.6 },
    ],
    sides: [
      {
        name: "Cilantro-Lime Rice",
        note: "Stir lime juice and chopped cilantro into fluffy white rice.",
        estCost: 1.7,
        caloriesPerServing: 190,
        ingredients: [
          { name: "long grain rice", quantity: "1.5 cups dry", category: "Pantry", estCost: 0.8 },
          { name: "lime", quantity: "1", category: "Produce", estCost: 0.4 },
          { name: "cilantro", quantity: "1/2 bunch", category: "Produce", estCost: 0.5 },
        ],
      },
      {
        name: "Quick Pickled Onions & Slaw",
        note: "Vinegared red onion and cabbage add crunch to every taco.",
        estCost: 2.0,
        caloriesPerServing: 35,
        ingredients: [
          { name: "red onion", quantity: "1", category: "Produce", estCost: 0.8 },
          { name: "green cabbage", quantity: "1/2 head", category: "Produce", estCost: 1.0 },
          { name: "white vinegar", quantity: "1/2 cup", category: "Pantry", estCost: 0.2 },
        ],
      },
    ],
  },
  {
    name: "One-Pot Creamy Tomato Pasta",
    cuisine: "Italian",
    tags: ["Italian", "Comfort", "Kid-friendly", "Quick", "Vegetarian"],
    servings: 4,
    caloriesPerServing: 560,
    proteinPerServing: 18,
    estimatedCost: 8.9,
    cookTimeMin: 30,
    appliance: "Stove",
    method: "Simmer penne right in the tomato-garlic sauce, finish with cream and parmesan.",
    ingredients: [
      { name: "penne pasta", quantity: "1 lb", category: "Pantry", estCost: 1.3 },
      { name: "crushed tomatoes", quantity: "1 can (28 oz)", category: "Pantry", estCost: 1.8 },
      { name: "heavy cream", quantity: "3/4 cup", category: "Dairy & Eggs", estCost: 1.6 },
      { name: "parmesan cheese", quantity: "3 oz", category: "Dairy & Eggs", estCost: 2.8 },
      { name: "garlic", quantity: "4 cloves", category: "Produce", estCost: 0.4 },
      { name: "yellow onion", quantity: "1", category: "Produce", estCost: 0.7 },
      { name: "fresh basil", quantity: "1/4 cup", category: "Produce", estCost: 0.3 },
    ],
    sides: [
      {
        name: "Garlic Bread",
        note: "Butter, garlic, and a bake until golden — non-negotiable with tomato pasta.",
        estCost: 2.4,
        caloriesPerServing: 180,
        ingredients: [
          { name: "french bread", quantity: "1 loaf", category: "Bakery", estCost: 1.5 },
          { name: "butter", quantity: "4 tbsp", category: "Dairy & Eggs", estCost: 0.6 },
          { name: "garlic", quantity: "3 cloves", category: "Produce", estCost: 0.3 },
        ],
      },
      {
        name: "Caesar-ish Salad",
        note: "Crisp romaine with parmesan and croutons.",
        estCost: 3.0,
        caloriesPerServing: 120,
        ingredients: [
          { name: "romaine lettuce", quantity: "1 head", category: "Produce", estCost: 1.8 },
          { name: "parmesan cheese", quantity: "1 oz", category: "Dairy & Eggs", estCost: 0.9 },
          { name: "croutons", quantity: "1 cup", category: "Bakery", estCost: 0.3 },
        ],
      },
    ],
  },
  {
    name: "Air Fryer Salmon with Honey Glaze",
    cuisine: "Mediterranean",
    tags: ["Mediterranean", "High-protein", "Low-cal", "Quick"],
    servings: 4,
    caloriesPerServing: 390,
    proteinPerServing: 35,
    estimatedCost: 16.8,
    cookTimeMin: 18,
    appliance: "Air fryer",
    method: "Air-fry salmon fillets brushed with honey-dijon glaze until just flaky.",
    ingredients: [
      { name: "salmon fillets", quantity: "4 (6 oz each)", category: "Meat & Seafood", estCost: 14.0 },
      { name: "honey", quantity: "2 tbsp", category: "Pantry", estCost: 0.4 },
      { name: "dijon mustard", quantity: "1 tbsp", category: "Pantry", estCost: 0.2 },
      { name: "lemon", quantity: "1", category: "Produce", estCost: 0.6 },
      { name: "garlic powder", quantity: "1 tsp", category: "Spices", estCost: 0.1 },
      { name: "olive oil", quantity: "1 tbsp", category: "Pantry", estCost: 0.2 },
    ],
    sides: [
      {
        name: "Roasted Asparagus",
        note: "Toss in the air fryer for the last 7 minutes alongside the salmon.",
        estCost: 3.2,
        caloriesPerServing: 45,
        ingredients: [
          { name: "asparagus", quantity: "1 lb", category: "Produce", estCost: 2.9 },
          { name: "olive oil", quantity: "1 tbsp", category: "Pantry", estCost: 0.2 },
          { name: "lemon", quantity: "1/2", category: "Produce", estCost: 0.3 },
        ],
      },
      {
        name: "Herbed Couscous",
        note: "Five-minute couscous with parsley and lemon zest.",
        estCost: 1.9,
        caloriesPerServing: 175,
        ingredients: [
          { name: "couscous", quantity: "1.5 cups dry", category: "Pantry", estCost: 1.4 },
          { name: "parsley", quantity: "1/4 bunch", category: "Produce", estCost: 0.5 },
        ],
      },
    ],
  },
  {
    name: "Instant Pot White Chicken Chili",
    cuisine: "American",
    tags: ["Comfort", "High-protein", "Meal-prep", "Budget"],
    servings: 6,
    caloriesPerServing: 410,
    proteinPerServing: 36,
    estimatedCost: 11.9,
    cookTimeMin: 40,
    appliance: "Instant Pot",
    method: "Pressure-cook chicken, white beans, and green chiles; shred and stir in a little cream cheese.",
    ingredients: [
      { name: "chicken breasts", quantity: "1.5 lb", category: "Meat & Seafood", estCost: 4.5 },
      { name: "white beans", quantity: "2 cans (15 oz)", category: "Pantry", estCost: 1.8 },
      { name: "diced green chiles", quantity: "2 small cans", category: "Pantry", estCost: 1.8 },
      { name: "chicken broth", quantity: "4 cups", category: "Pantry", estCost: 1.5 },
      { name: "yellow onion", quantity: "1", category: "Produce", estCost: 0.7 },
      { name: "cream cheese", quantity: "4 oz", category: "Dairy & Eggs", estCost: 1.3 },
      { name: "cumin", quantity: "1 tbsp", category: "Spices", estCost: 0.3 },
    ],
    sides: [
      {
        name: "Cornbread",
        note: "Sweet, golden, and perfect for dunking — one boxed mix, one egg.",
        estCost: 2.1,
        caloriesPerServing: 210,
        ingredients: [
          { name: "cornbread mix", quantity: "1 box", category: "Bakery", estCost: 1.2 },
          { name: "eggs", quantity: "1", category: "Dairy & Eggs", estCost: 0.3 },
          { name: "milk", quantity: "1/3 cup", category: "Dairy & Eggs", estCost: 0.2 },
          { name: "butter", quantity: "2 tbsp", category: "Dairy & Eggs", estCost: 0.4 },
        ],
      },
      {
        name: "Tortilla Chips & Lime",
        note: "For topping — crunch plus a squeeze of lime brightens the bowl.",
        estCost: 2.4,
        caloriesPerServing: 140,
        ingredients: [
          { name: "tortilla chips", quantity: "1 bag", category: "Pantry", estCost: 2.0 },
          { name: "lime", quantity: "1", category: "Produce", estCost: 0.4 },
        ],
      },
    ],
  },
];

export function seedIfEmpty() {
  if (recipeCount() > 0) return false;
  for (const recipe of seedRecipes) {
    createRecipe(recipe, "seed");
  }
  console.log(`Seeded ${seedRecipes.length} starter recipes.`);
  return true;
}
