/**
 * Generate the service worker after a Vite build.
 *
 * The app is fully static and self-contained, so the whole thing can be
 * precached and then served cache-first: once installed it runs with no
 * network at all. Asset filenames are content-hashed by Vite, so the precache
 * list has to be read from the actual build output rather than hard-coded, and
 * the cache name is derived from that list so a new build cleanly replaces the
 * old cache.
 */
import { readdirSync, readFileSync, writeFileSync, statSync } from 'node:fs';
import { join, relative } from 'node:path';
import { createHash } from 'node:crypto';

const DIST = 'dist';

function walk(dir) {
  return readdirSync(dir).flatMap((entry) => {
    const full = join(dir, entry);
    return statSync(full).isDirectory() ? walk(full) : [full];
  });
}

// Everything Vite emitted, as URLs relative to the deploy root.
const files = walk(DIST)
  .map((f) => relative(DIST, f).split('\\').join('/'))
  .filter((f) => f !== 'sw.js')
  .sort();

const base = JSON.parse(readFileSync('package.json', 'utf8')).version;
const revision = createHash('sha256')
  .update(files.join('|') + base)
  .digest('hex')
  .slice(0, 12);

const sw = `/* Generated by scripts/build-sw.mjs -- do not edit by hand. */
const CACHE = 'catan-map-forge-${revision}';
const ASSETS = ${JSON.stringify(files, null, 2)};

// Precache the whole app shell on install.
self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE)
      .then((cache) => cache.addAll(ASSETS.map((f) => new URL(f, self.registration.scope).toString())))
      .then(() => self.skipWaiting()),
  );
});

// Drop caches from previous builds.
self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // Navigations always resolve to the cached app shell, so a cold launch with
  // no network still opens the app.
  if (request.mode === 'navigate') {
    event.respondWith(
      caches.match(new URL('index.html', self.registration.scope).toString())
        .then((cached) => cached || fetch(request)),
    );
    return;
  }

  // Everything else: serve from cache, fall back to network, and backfill the
  // cache so anything missed at install time is available next launch.
  event.respondWith(
    caches.match(request).then((cached) => {
      if (cached) return cached;
      return fetch(request).then((response) => {
        if (response.ok && response.type === 'basic') {
          const copy = response.clone();
          caches.open(CACHE).then((cache) => cache.put(request, copy));
        }
        return response;
      });
    }),
  );
});
`;

writeFileSync(join(DIST, 'sw.js'), sw);

// Tell GitHub Pages to serve the build verbatim rather than running Jekyll.
writeFileSync(join(DIST, '.nojekyll'), '');

console.log(`sw.js generated: ${files.length} files precached, cache catan-map-forge-${revision}`);
